export const vehicles = [
  {
    brand: "Abarth",
    models: [
      { name: "500 1.4 T", type: "auto", avgConsumptionLPer100km: 7.8 },
      { name: "595 Competizione", type: "deportivo", avgConsumptionLPer100km: 8.5 },
      { name: "Pulse Abarth", type: "SUV", avgConsumptionLPer100km: 8.2 },
      { name: "Fastback Abarth", type: "SUV", avgConsumptionLPer100km: 8.3 },
    ],
  },
  {
    brand: "Alfa Romeo",
    models: [
      { name: "Mito 1.4 T", type: "auto", avgConsumptionLPer100km: 7.5 },
      { name: "Giulietta 1.4 T", type: "auto", avgConsumptionLPer100km: 8.0 },
      { name: "Giulia 2.0 T", type: "auto", avgConsumptionLPer100km: 8.5 },
      { name: "Giulia Quadrifoglio", type: "deportivo", avgConsumptionLPer100km: 12.5 },
      { name: "Stelvio 2.0 T", type: "SUV", avgConsumptionLPer100km: 9.5 },
      { name: "Stelvio Quadrifoglio", type: "SUV", avgConsumptionLPer100km: 13.0 },
      { name: "Tonale Hybrid", type: "SUV", avgConsumptionLPer100km: 6.0 },
      { name: "4C", type: "deportivo", avgConsumptionLPer100km: 9.0 },
    ],
  },
  {
    brand: "Audi",
    models: [
      { name: "A1 1.4 TFSI", type: "auto", avgConsumptionLPer100km: 7.0 },
      { name: "A3 1.4/1.5 TFSI", type: "auto", avgConsumptionLPer100km: 7.2 },
      { name: "S3 2.0 TFSI", type: "deportivo", avgConsumptionLPer100km: 9.5 },
      { name: "RS3 2.5 TFSI", type: "deportivo", avgConsumptionLPer100km: 11.0 },
      { name: "A4 2.0 TFSI", type: "auto", avgConsumptionLPer100km: 8.0 },
      { name: "S4 3.0 TFSI", type: "deportivo", avgConsumptionLPer100km: 10.5 },
      { name: "RS4 Avant", type: "deportivo", avgConsumptionLPer100km: 12.0 },
      { name: "A5 Coupé/Sportback", type: "auto", avgConsumptionLPer100km: 8.2 },
      { name: "RS5", type: "deportivo", avgConsumptionLPer100km: 12.5 },
      { name: "A6 3.0 TFSI", type: "auto", avgConsumptionLPer100km: 9.0 },
      { name: "RS6 Avant", type: "deportivo", avgConsumptionLPer100km: 14.5 },
      { name: "A7 Sportback", type: "auto", avgConsumptionLPer100km: 9.2 },
      { name: "RS7", type: "deportivo", avgConsumptionLPer100km: 14.0 },
      { name: "A8 L", type: "auto", avgConsumptionLPer100km: 10.5 },
      { name: "Q2 1.4 TFSI", type: "SUV", avgConsumptionLPer100km: 7.5 },
      { name: "Q3 1.4/2.0 TFSI", type: "SUV", avgConsumptionLPer100km: 8.5 },
      { name: "RSQ3", type: "SUV", avgConsumptionLPer100km: 11.5 },
      { name: "Q5 2.0 TDI/TFSI", type: "SUV", avgConsumptionLPer100km: 9.0 },
      { name: "SQ5", type: "SUV", avgConsumptionLPer100km: 11.0 },
      { name: "Q7 3.0 TDI/TFSI", type: "SUV", avgConsumptionLPer100km: 11.0 },
      { name: "Q8 3.0 TFSI", type: "SUV", avgConsumptionLPer100km: 11.5 },
      { name: "RSQ8", type: "SUV", avgConsumptionLPer100km: 15.0 },
      { name: "e-tron", type: "auto", avgConsumptionLPer100km: 0.0 },
      { name: "e-tron GT", type: "deportivo", avgConsumptionLPer100km: 0.0 },
      { name: "TT / TTS", type: "deportivo", avgConsumptionLPer100km: 9.5 },
      { name: "R8 V10", type: "deportivo", avgConsumptionLPer100km: 16.0 },
    ],
  },
  {
    brand: "BAIC",
    models: [
      { name: "D20", type: "auto", avgConsumptionLPer100km: 7.5 },
      { name: "X25 1.5", type: "auto", avgConsumptionLPer100km: 8.5 },
      { name: "X35 1.5", type: "auto", avgConsumptionLPer100km: 9.0 },
      { name: "X55 1.5 T", type: "SUV", avgConsumptionLPer100km: 9.2 },
      { name: "BJ40 Plus", type: "SUV", avgConsumptionLPer100km: 12.0 },
    ],
  },
  {
    brand: "Bajaj",
    models: [
      { name: "Boxer 150", type: "moto", avgConsumptionLPer100km: 3.0 },
      { name: "Rouser 125", type: "moto", avgConsumptionLPer100km: 2.5 },
      { name: "Rouser 135", type: "moto", avgConsumptionLPer100km: 3.0 },
      { name: "Rouser 160 NS", type: "moto", avgConsumptionLPer100km: 3.2 },
      { name: "Rouser 200 NS", type: "moto", avgConsumptionLPer100km: 3.5 },
      { name: "Dominar 250", type: "moto", avgConsumptionLPer100km: 3.5 },
      { name: "Dominar 400", type: "moto", avgConsumptionLPer100km: 4.0 },
      { name: "Avenger 220", type: "moto", avgConsumptionLPer100km: 3.8 },
    ],
  },
  {
    brand: "Benelli",
    models: [
      { name: "TNT 135", type: "moto", avgConsumptionLPer100km: 2.8 },
      { name: "TNT 150", type: "moto", avgConsumptionLPer100km: 3.0 },
      { name: "TNT 300 / 302S", type: "moto", avgConsumptionLPer100km: 4.0 },
      { name: "Leoncino 250", type: "moto", avgConsumptionLPer100km: 3.5 },
      { name: "Leoncino 500", type: "moto", avgConsumptionLPer100km: 4.5 },
      { name: "TRK 502 / 502X", type: "moto", avgConsumptionLPer100km: 4.8 },
      { name: "752S", type: "moto", avgConsumptionLPer100km: 5.5 },
      { name: "Imperiale 400", type: "moto", avgConsumptionLPer100km: 3.8 },
    ],
  },
  {
    brand: "BMW",
    models: [
      { name: "Serie 1 118i", type: "auto", avgConsumptionLPer100km: 7.0 },
      { name: "M135i", type: "deportivo", avgConsumptionLPer100km: 9.0 },
      { name: "Serie 2 Coupé/Gran Coupé", type: "auto", avgConsumptionLPer100km: 7.2 },
      { name: "M2", type: "deportivo", avgConsumptionLPer100km: 11.0 },
      { name: "Serie 3 320i/330i", type: "auto", avgConsumptionLPer100km: 7.5 },
      { name: "M3 Competition", type: "deportivo", avgConsumptionLPer100km: 12.5 },
      { name: "Serie 4 Coupé/Gran Coupé", type: "auto", avgConsumptionLPer100km: 7.8 },
      { name: "M4 Competition", type: "deportivo", avgConsumptionLPer100km: 12.5 },
      { name: "Serie 5 530i/540i", type: "auto", avgConsumptionLPer100km: 8.5 },
      { name: "M5", type: "deportivo", avgConsumptionLPer100km: 13.5 },
      { name: "Serie 7", type: "auto", avgConsumptionLPer100km: 10.0 },
      { name: "Serie 8", type: "deportivo", avgConsumptionLPer100km: 11.0 },
      { name: "X1 20i", type: "SUV", avgConsumptionLPer100km: 8.0 },
      { name: "X2 20i/M35i", type: "SUV", avgConsumptionLPer100km: 8.2 },
      { name: "X3 20i/30i/20d", type: "SUV", avgConsumptionLPer100km: 8.8 },
      { name: "X4 30i", type: "SUV", avgConsumptionLPer100km: 9.0 },
      { name: "X5 40i/30d", type: "SUV", avgConsumptionLPer100km: 10.5 },
      { name: "X6 40i", type: "SUV", avgConsumptionLPer100km: 10.8 },
      { name: "X7", type: "SUV", avgConsumptionLPer100km: 12.0 },
      { name: "Z4 Roadster", type: "deportivo", avgConsumptionLPer100km: 8.5 },
      { name: "iX / i4 / iX1", type: "auto", avgConsumptionLPer100km: 0.0 },
    ],
  },
  {
    brand: "BYD",
    models: [
      { name: "Dolphin (EV)", type: "auto", avgConsumptionLPer100km: 0.0 },
      { name: "Yuan Plus (EV)", type: "SUV", avgConsumptionLPer100km: 0.0 },
      { name: "Han (EV)", type: "auto", avgConsumptionLPer100km: 0.0 },
      { name: "Tang (EV)", type: "SUV", avgConsumptionLPer100km: 0.0 },
      { name: "Song Plus DM-i", type: "SUV", avgConsumptionLPer100km: 4.5 },
    ],
  },
  {
    brand: "Changan",
    models: [
      { name: "CS15 1.5", type: "SUV", avgConsumptionLPer100km: 8.5 },
      { name: "CS35 Plus 1.6", type: "SUV", avgConsumptionLPer100km: 9.0 },
      { name: "CS55 Plus", type: "SUV", avgConsumptionLPer100km: 9.2 },
      { name: "CS75 Plus", type: "SUV", avgConsumptionLPer100km: 9.5 },
      { name: "MD201", type: "utilitario", avgConsumptionLPer100km: 8.0 },
    ],
  },
  {
    brand: "Chery",
    models: [
      { name: "QQ 1.0", type: "auto", avgConsumptionLPer100km: 6.5 },
      { name: "Fulwin", type: "auto", avgConsumptionLPer100km: 7.8 },
      { name: "Arrizo 5", type: "auto", avgConsumptionLPer100km: 8.0 },
      { name: "Tiggo 2 / 2 Pro", type: "SUV", avgConsumptionLPer100km: 8.2 },
      { name: "Tiggo 3", type: "SUV", avgConsumptionLPer100km: 9.0 },
      { name: "Tiggo 4 / 4 Pro", type: "SUV", avgConsumptionLPer100km: 8.5 },
      { name: "Tiggo 8 / 8 Pro", type: "SUV", avgConsumptionLPer100km: 10.0 },
    ],
  },
  {
    brand: "Chevrolet",
    models: [
      { name: "Onix 1.0 T", type: "auto", avgConsumptionLPer100km: 8.1 },
      { name: "Onix Joy/1.4", type: "auto", avgConsumptionLPer100km: 7.6 },
      { name: "Onix Plus 1.0 T", type: "auto", avgConsumptionLPer100km: 8.1 },
      { name: "Prisma", type: "auto", avgConsumptionLPer100km: 7.8 },
      { name: "Cruze 1.4 T", type: "auto", avgConsumptionLPer100km: 7.5 },
      { name: "Tracker 1.2 T", type: "SUV", avgConsumptionLPer100km: 8.3 },
      { name: "Equinox 1.5 T", type: "SUV", avgConsumptionLPer100km: 9.5 },
      { name: "Trailblazer 2.8 TDi", type: "SUV", avgConsumptionLPer100km: 10.5 },
      { name: "Spin", type: "utilitario", avgConsumptionLPer100km: 8.8 },
      { name: "Montana 1.2 T", type: "pickup", avgConsumptionLPer100km: 8.5 },
      { name: "S10 2.8 TDi", type: "pickup", avgConsumptionLPer100km: 9.5 },
      { name: "Silverado", type: "pickup", avgConsumptionLPer100km: 14.0 },
      { name: "Camaro SS", type: "deportivo", avgConsumptionLPer100km: 15.0 },
      { name: "Corvette", type: "deportivo", avgConsumptionLPer100km: 14.0 },
    ],
  },
  {
    brand: "Chrysler",
    models: [
      { name: "PT Cruiser 2.4", type: "auto", avgConsumptionLPer100km: 11.0 },
      { name: "300C 3.6/5.7", type: "auto", avgConsumptionLPer100km: 12.5 },
      { name: "Town & Country / Pacifica", type: "utilitario", avgConsumptionLPer100km: 11.5 },
    ],
  },
  {
    brand: "Citroën",
    models: [
      { name: "C3 1.4/1.6 (Viejo)", type: "auto", avgConsumptionLPer100km: 7.5 },
      { name: "C3 (Nuevo) 1.2/1.6", type: "auto", avgConsumptionLPer100km: 7.0 },
      { name: "C3 Aircross", type: "SUV", avgConsumptionLPer100km: 7.8 },
      { name: "C4 Cactus 1.6/THP", type: "SUV", avgConsumptionLPer100km: 7.8 },
      { name: "C4 Lounge 1.6 THP", type: "auto", avgConsumptionLPer100km: 8.2 },
      { name: "C5 Aircross", type: "SUV", avgConsumptionLPer100km: 8.5 },
      { name: "C-Elysée", type: "auto", avgConsumptionLPer100km: 7.2 },
      { name: "Berlingo 1.6", type: "utilitario", avgConsumptionLPer100km: 8.5 },
      { name: "Jumpy", type: "utilitario", avgConsumptionLPer100km: 8.0 },
    ],
  },
  {
    brand: "Corven",
    models: [
      { name: "Energy 110", type: "moto", avgConsumptionLPer100km: 2.5 },
      { name: "Mirage 110", type: "moto", avgConsumptionLPer100km: 2.5 },
      { name: "Hunter 150", type: "moto", avgConsumptionLPer100km: 3.0 },
      { name: "Triax 150", type: "moto", avgConsumptionLPer100km: 3.0 },
      { name: "Triax 250", type: "moto", avgConsumptionLPer100km: 3.8 },
      { name: "TXR 250", type: "moto", avgConsumptionLPer100km: 4.0 },
    ],
  },
  {
    brand: "Daewoo",
    models: [
      { name: "Tico 0.8", type: "auto", avgConsumptionLPer100km: 6.0 },
      { name: "Matiz", type: "auto", avgConsumptionLPer100km: 6.2 },
      { name: "Lanos", type: "auto", avgConsumptionLPer100km: 7.5 },
      { name: "Nubira", type: "auto", avgConsumptionLPer100km: 8.5 },
      { name: "Espero 1.5/1.8", type: "auto", avgConsumptionLPer100km: 9.0 },
    ],
  },
  {
    brand: "Daihatsu",
    models: [
      { name: "Charade 1.3", type: "auto", avgConsumptionLPer100km: 7.0 },
      { name: "Cuore 0.8/1.0", type: "auto", avgConsumptionLPer100km: 6.0 },
      { name: "Terios", type: "SUV", avgConsumptionLPer100km: 8.5 },
      { name: "Feroza", type: "SUV", avgConsumptionLPer100km: 10.0 },
    ],
  },
  {
    brand: "Datsun",
    models: [
      { name: "120Y/140Y", type: "auto", avgConsumptionLPer100km: 9.0 },
      { name: "280 ZX", type: "deportivo", avgConsumptionLPer100km: 12.0 },
    ],
  },
  {
    brand: "Dodge",
    models: [
      { name: "1500 1.8/2.0", type: "auto", avgConsumptionLPer100km: 11.0 },
      { name: "Journey 2.4", type: "SUV", avgConsumptionLPer100km: 12.0 },
      { name: "RAM 1500 (viejas Dodge)", type: "pickup", avgConsumptionLPer100km: 14.0 },
      { name: "Challenger", type: "deportivo", avgConsumptionLPer100km: 14.5 },
      { name: "Durango", type: "SUV", avgConsumptionLPer100km: 13.0 },
    ],
  },
  {
    brand: "Ferrari",
    models: [
      { name: "360 Modena", type: "deportivo", avgConsumptionLPer100km: 16.0 },
      { name: "F430", type: "deportivo", avgConsumptionLPer100km: 16.5 },
      { name: "458 Italia", type: "deportivo", avgConsumptionLPer100km: 15.0 },
      { name: "488 GTB", type: "deportivo", avgConsumptionLPer100km: 15.0 },
      { name: "F8 Tributo", type: "deportivo", avgConsumptionLPer100km: 14.5 },
      { name: "296 GTB (Híbrido)", type: "deportivo", avgConsumptionLPer100km: 8.0 },
      { name: "SF90 Stradale", type: "deportivo", avgConsumptionLPer100km: 7.5 },
      { name: "Roma", type: "deportivo", avgConsumptionLPer100km: 12.0 },
    ],
  },
  {
    brand: "Fiat",
    models: [
      { name: "Uno/Way 1.4", type: "auto", avgConsumptionLPer100km: 7.8 },
      { name: "Palio 1.4/1.6", type: "auto", avgConsumptionLPer100km: 8.0 },
      { name: "Siena / Grand Siena", type: "auto", avgConsumptionLPer100km: 8.2 },
      { name: "Punto 1.4/1.6", type: "auto", avgConsumptionLPer100km: 8.0 },
      { name: "500 / 500e", type: "auto", avgConsumptionLPer100km: 6.5 },
      { name: "Mobi 1.0", type: "auto", avgConsumptionLPer100km: 7.0 },
      { name: "Cronos 1.3", type: "auto", avgConsumptionLPer100km: 7.5 },
      { name: "Cronos 1.8", type: "auto", avgConsumptionLPer100km: 8.8 },
      { name: "Argo 1.3/1.8", type: "auto", avgConsumptionLPer100km: 7.8 },
      { name: "Pulse 1.3/1.0 T", type: "SUV", avgConsumptionLPer100km: 7.9 },
      { name: "Fastback 1.3 T/1.0 T", type: "SUV", avgConsumptionLPer100km: 8.1 },
      { name: "Strada 1.4/1.3", type: "pickup", avgConsumptionLPer100km: 8.5 },
      { name: "Toro 2.0 TDi/1.8/1.3 T", type: "pickup", avgConsumptionLPer100km: 9.5 },
      { name: "Fiorino", type: "utilitario", avgConsumptionLPer100km: 8.0 },
      { name: "Ducato", type: "utilitario", avgConsumptionLPer100km: 10.0 },
    ],
  },
  {
    brand: "Ford",
    models: [
      { name: "Ka 1.5", type: "auto", avgConsumptionLPer100km: 7.5 },
      { name: "Fiesta KD 1.6", type: "auto", avgConsumptionLPer100km: 7.8 },
      { name: "Focus 1.6/2.0", type: "auto", avgConsumptionLPer100km: 8.2 },
      { name: "Mondeo / Fusion", type: "auto", avgConsumptionLPer100km: 9.5 },
      { name: "EcoSport 1.5/2.0", type: "SUV", avgConsumptionLPer100km: 8.8 },
      { name: "Territory 1.5 T/1.8 T", type: "SUV", avgConsumptionLPer100km: 9.5 },
      { name: "Kuga Híbrida/2.0 T", type: "SUV", avgConsumptionLPer100km: 5.5 },
      { name: "Bronco Sport 1.5/2.0", type: "SUV", avgConsumptionLPer100km: 9.8 },
      { name: "Maverick Híbrida/2.0 T", type: "pickup", avgConsumptionLPer100km: 6.0 },
      { name: "Ranger 2.2/3.2/V6 New", type: "pickup", avgConsumptionLPer100km: 9.5 },
      { name: "Ranger Raptor", type: "pickup", avgConsumptionLPer100km: 13.0 },
      { name: "F-150 / F-150 Raptor", type: "pickup", avgConsumptionLPer100km: 16.0 },
      { name: "Mustang GT", type: "deportivo", avgConsumptionLPer100km: 14.0 },
      { name: "Transit", type: "utilitario", avgConsumptionLPer100km: 10.0 },
    ],
  },
  {
    brand: "Geely",
    models: [
      { name: "LC 1.0/1.3", type: "auto", avgConsumptionLPer100km: 7.5 },
      { name: "515 1.5", type: "auto", avgConsumptionLPer100km: 8.0 },
      { name: "Emgrand 7", type: "auto", avgConsumptionLPer100km: 8.5 },
      { name: "Emgrand X7 Sport", type: "SUV", avgConsumptionLPer100km: 10.0 },
    ],
  },
  {
    brand: "Gilera",
    models: [
      { name: "Smash 110", type: "moto", avgConsumptionLPer100km: 2.5 },
      { name: "VC 150", type: "moto", avgConsumptionLPer100km: 3.0 },
      { name: "VC 200", type: "moto", avgConsumptionLPer100km: 3.5 },
      { name: "Sahel 150", type: "moto", avgConsumptionLPer100km: 3.2 },
      { name: "AC4 250", type: "moto", avgConsumptionLPer100km: 4.0 },
    ],
  },
  {
    brand: "Haval",
    models: [
      { name: "H1", type: "SUV", avgConsumptionLPer100km: 8.0 },
      { name: "H2 1.5 T", type: "SUV", avgConsumptionLPer100km: 9.0 },
      { name: "Jolion", type: "SUV", avgConsumptionLPer100km: 8.8 },
      { name: "H6 2.0 T", type: "SUV", avgConsumptionLPer100km: 10.0 },
      { name: "H9", type: "SUV", avgConsumptionLPer100km: 12.0 },
    ],
  },
  {
    brand: "Honda",
    models: [
      { name: "Fit 1.4/1.5", type: "auto", avgConsumptionLPer100km: 7.2 },
      { name: "City 1.5", type: "auto", avgConsumptionLPer100km: 7.4 },
      { name: "Civic 1.8/2.0/1.5 T", type: "auto", avgConsumptionLPer100km: 8.0 },
      { name: "Civic Type R", type: "deportivo", avgConsumptionLPer100km: 10.0 },
      { name: "Accord", type: "auto", avgConsumptionLPer100km: 9.0 },
      { name: "WR-V", type: "SUV", avgConsumptionLPer100km: 7.8 },
      { name: "HR-V 1.8/1.5", type: "SUV", avgConsumptionLPer100km: 8.5 },
      { name: "ZR-V", type: "SUV", avgConsumptionLPer100km: 8.8 },
      { name: "CR-V", type: "SUV", avgConsumptionLPer100km: 9.5 },
      { name: "Pilot", type: "SUV", avgConsumptionLPer100km: 12.0 },
      { name: "Wave 110", type: "moto", avgConsumptionLPer100km: 2.2 },
      { name: "GLH 150 Gaucha", type: "moto", avgConsumptionLPer100km: 2.8 },
      { name: "Titan 150", type: "moto", avgConsumptionLPer100km: 3.0 },
      { name: "Twister 250/300", type: "moto", avgConsumptionLPer100km: 3.8 },
      { name: "Tornado 250", type: "moto", avgConsumptionLPer100km: 4.0 },
      { name: "Africa Twin", type: "moto", avgConsumptionLPer100km: 5.5 },
    ],
  },
  {
    brand: "Hyundai",
    models: [
      { name: "i10/Grand i10", type: "auto", avgConsumptionLPer100km: 6.8 },
      { name: "i20/Accent", type: "auto", avgConsumptionLPer100km: 7.2 },
      { name: "i30/Elantra", type: "auto", avgConsumptionLPer100km: 7.8 },
      { name: "Veloster", type: "auto", avgConsumptionLPer100km: 8.5 },
      { name: "Kona", type: "SUV", avgConsumptionLPer100km: 7.5 },
      { name: "Creta", type: "SUV", avgConsumptionLPer100km: 8.2 },
      { name: "Tucson", type: "SUV", avgConsumptionLPer100km: 8.8 },
      { name: "Santa Fe", type: "SUV", avgConsumptionLPer100km: 9.5 },
      { name: "Palisade", type: "SUV", avgConsumptionLPer100km: 11.5 },
      { name: "H1 / Staria", type: "utilitario", avgConsumptionLPer100km: 10.0 },
    ],
  },
  {
    brand: "Isuzu",
    models: [
      { name: "D-Max 3.0 TDi", type: "pickup", avgConsumptionLPer100km: 9.5 },
      { name: "NPR 75", type: "camion", avgConsumptionLPer100km: 15.0 },
    ],
  },
  {
    brand: "Iveco",
    models: [
      { name: "Daily 35S/55C/70C", type: "camioneta", avgConsumptionLPer100km: 14.0 },
      { name: "Tector", type: "camion", avgConsumptionLPer100km: 22.0 },
      { name: "Stralis", type: "camion", avgConsumptionLPer100km: 28.0 },
    ],
  },
  {
    brand: "JAC Motors",
    models: [
      { name: "S2 1.5", type: "SUV", avgConsumptionLPer100km: 8.5 },
      { name: "S3 1.6", type: "SUV", avgConsumptionLPer100km: 9.0 },
      { name: "S4", type: "SUV", avgConsumptionLPer100km: 9.2 },
      { name: "T6 2.0 TDi", type: "pickup", avgConsumptionLPer100km: 10.0 },
      { name: "T8", type: "pickup", avgConsumptionLPer100km: 10.5 },
    ],
  },
  {
    brand: "Jaguar",
    models: [
      { name: "XE 2.0 T", type: "auto", avgConsumptionLPer100km: 8.5 },
      { name: "XF", type: "auto", avgConsumptionLPer100km: 9.0 },
      { name: "E-Pace", type: "SUV", avgConsumptionLPer100km: 9.0 },
      { name: "F-Pace 2.0 T", type: "SUV", avgConsumptionLPer100km: 9.5 },
      { name: "F-Type", type: "deportivo", avgConsumptionLPer100km: 11.0 },
      { name: "I-Pace", type: "SUV", avgConsumptionLPer100km: 0.0 },
    ],
  },
  {
    brand: "Jeep",
    models: [
      { name: "Renegade 1.8/1.3 T", type: "SUV", avgConsumptionLPer100km: 9.0 },
      { name: "Compass 2.0/1.3 T", type: "SUV", avgConsumptionLPer100km: 9.5 },
      { name: "Commander 2.0 TDi/1.3 T", type: "SUV", avgConsumptionLPer100km: 9.8 },
      { name: "Cherokee/Grand Cherokee", type: "SUV", avgConsumptionLPer100km: 11.5 },
      { name: "Wrangler Rubicon/Sahara", type: "SUV", avgConsumptionLPer100km: 13.0 },
      { name: "Gladiator", type: "pickup", avgConsumptionLPer100km: 13.5 },
    ],
  },
  {
    brand: "Jetour",
    models: [
      { name: "X70 1.5/1.6 T", type: "SUV", avgConsumptionLPer100km: 9.5 },
      { name: "X70 Plus", type: "SUV", avgConsumptionLPer100km: 9.8 },
      { name: "Dashing", type: "SUV", avgConsumptionLPer100km: 9.0 },
    ],
  },
  {
    brand: "Kia",
    models: [
      { name: "Picanto/Morning", type: "auto", avgConsumptionLPer100km: 6.5 },
      { name: "Rio 1.4", type: "auto", avgConsumptionLPer100km: 7.2 },
      { name: "Cerato 1.6/2.0", type: "auto", avgConsumptionLPer100km: 7.8 },
      { name: "Soul", type: "auto", avgConsumptionLPer100km: 8.0 },
      { name: "Seltos", type: "SUV", avgConsumptionLPer100km: 8.5 },
      { name: "Sportage", type: "SUV", avgConsumptionLPer100km: 8.8 },
      { name: "Sorento", type: "SUV", avgConsumptionLPer100km: 9.5 },
      { name: "Carnival", type: "utilitario", avgConsumptionLPer100km: 10.5 },
      { name: "K2500", type: "utilitario", avgConsumptionLPer100km: 10.0 },
    ],
  },
  {
    brand: "KTM",
    models: [
      { name: "Duke 200", type: "moto", avgConsumptionLPer100km: 3.8 },
      { name: "Duke 250", type: "moto", avgConsumptionLPer100km: 4.0 },
      { name: "Duke 390", type: "moto", avgConsumptionLPer100km: 4.2 },
      { name: "RC 200/390", type: "moto", avgConsumptionLPer100km: 4.0 },
      { name: "Adventure 390", type: "moto", avgConsumptionLPer100km: 4.5 },
      { name: "Adventure 790/890", type: "moto", avgConsumptionLPer100km: 5.5 },
      { name: "Super Adventure 1290", type: "moto", avgConsumptionLPer100km: 6.5 },
    ],
  },
  {
    brand: "Land Rover",
    models: [
      { name: "Freelander 2", type: "SUV", avgConsumptionLPer100km: 10.5 },
      { name: "Discovery Sport", type: "SUV", avgConsumptionLPer100km: 10.5 },
      { name: "Discovery", type: "SUV", avgConsumptionLPer100km: 12.0 },
      { name: "Range Rover Evoque", type: "SUV", avgConsumptionLPer100km: 9.8 },
      { name: "Range Rover Velar", type: "SUV", avgConsumptionLPer100km: 10.5 },
      { name: "Range Rover Sport", type: "SUV", avgConsumptionLPer100km: 11.5 },
      { name: "Defender", type: "SUV", avgConsumptionLPer100km: 11.0 },
    ],
  },
  {
    brand: "Lexus",
    models: [
      { name: "IS 300h", type: "auto", avgConsumptionLPer100km: 5.5 },
      { name: "ES 300h", type: "auto", avgConsumptionLPer100km: 5.8 },
      { name: "NX 300h/350h", type: "SUV", avgConsumptionLPer100km: 6.5 },
      { name: "RX 450h", type: "SUV", avgConsumptionLPer100km: 7.2 },
      { name: "LX 570/600", type: "SUV", avgConsumptionLPer100km: 14.0 },
      { name: "LC 500", type: "deportivo", avgConsumptionLPer100km: 12.0 },
    ],
  },
  {
    brand: "Lifan",
    models: [
      { name: "X50", type: "auto", avgConsumptionLPer100km: 7.5 },
      { name: "X60 1.8", type: "SUV", avgConsumptionLPer100km: 10.0 },
      { name: "X70", type: "SUV", avgConsumptionLPer100km: 10.2 },
      { name: "Myway", type: "SUV", avgConsumptionLPer100km: 9.8 },
      { name: "Foison 1.3", type: "utilitario", avgConsumptionLPer100km: 9.5 },
    ],
  },
  {
    brand: "Maserati",
    models: [
      { name: "Ghibli", type: "auto", avgConsumptionLPer100km: 13.0 },
      { name: "Quattroporte", type: "auto", avgConsumptionLPer100km: 14.0 },
      { name: "Levante", type: "SUV", avgConsumptionLPer100km: 14.0 },
      { name: "Grecale", type: "SUV", avgConsumptionLPer100km: 11.0 },
      { name: "GranTurismo", type: "deportivo", avgConsumptionLPer100km: 15.0 },
      { name: "MC20", type: "deportivo", avgConsumptionLPer100km: 12.5 },
    ],
  },
  {
    brand: "Mazda",
    models: [
      { name: "Mazda 2", type: "auto", avgConsumptionLPer100km: 6.5 },
      { name: "Mazda 3", type: "auto", avgConsumptionLPer100km: 7.5 },
      { name: "Mazda 6", type: "auto", avgConsumptionLPer100km: 8.2 },
      { name: "CX-3", type: "SUV", avgConsumptionLPer100km: 8.0 },
      { name: "CX-30", type: "SUV", avgConsumptionLPer100km: 8.5 },
      { name: "CX-5", type: "SUV", avgConsumptionLPer100km: 8.8 },
      { name: "CX-9", type: "SUV", avgConsumptionLPer100km: 11.0 },
      { name: "MX-5 Miata", type: "deportivo", avgConsumptionLPer100km: 7.5 },
    ],
  },
  {
    brand: "Mercedes-Benz",
    models: [
      { name: "Clase A 200/250", type: "auto", avgConsumptionLPer100km: 7.0 },
      { name: "A35/A45 AMG", type: "deportivo", avgConsumptionLPer100km: 10.5 },
      { name: "Clase C 200/300", type: "auto", avgConsumptionLPer100km: 7.5 },
      { name: "C43/C63 AMG", type: "deportivo", avgConsumptionLPer100km: 12.0 },
      { name: "Clase E 300/450", type: "auto", avgConsumptionLPer100km: 8.5 },
      { name: "Clase S 500", type: "auto", avgConsumptionLPer100km: 10.0 },
      { name: "CLA 200/250", type: "auto", avgConsumptionLPer100km: 7.2 },
      { name: "GLA 200/250", type: "SUV", avgConsumptionLPer100km: 7.8 },
      { name: "GLB 200/250", type: "SUV", avgConsumptionLPer100km: 8.0 },
      { name: "GLC 300/Coupe", type: "SUV", avgConsumptionLPer100km: 8.8 },
      { name: "GLE 450/53 AMG", type: "SUV", avgConsumptionLPer100km: 10.5 },
      { name: "GLS 450", type: "SUV", avgConsumptionLPer100km: 11.5 },
      { name: "Clase G 500/63 AMG", type: "SUV", avgConsumptionLPer100km: 16.0 },
      { name: "AMG GT", type: "deportivo", avgConsumptionLPer100km: 14.0 },
      { name: "Sprinter 311/415/515", type: "utilitario", avgConsumptionLPer100km: 13.0 },
      { name: "Vito", type: "utilitario", avgConsumptionLPer100km: 9.0 },
    ],
  },
  {
    brand: "Mini",
    models: [
      { name: "Cooper 3 Puertas 1.5 T", type: "auto", avgConsumptionLPer100km: 7.0 },
      { name: "Cooper S 2.0 T", type: "deportivo", avgConsumptionLPer100km: 8.5 },
      { name: "John Cooper Works (JCW)", type: "deportivo", avgConsumptionLPer100km: 9.5 },
      { name: "Cooper 5 Puertas", type: "auto", avgConsumptionLPer100km: 7.5 },
      { name: "Clubman", type: "auto", avgConsumptionLPer100km: 8.0 },
      { name: "Countryman", type: "SUV", avgConsumptionLPer100km: 8.5 },
    ],
  },
  {
    brand: "Mitsubishi",
    models: [
      { name: "Lancer 2.0", type: "auto", avgConsumptionLPer100km: 9.0 },
      { name: "Lancer Evolution", type: "deportivo", avgConsumptionLPer100km: 13.0 },
      { name: "ASX / Outlander Sport", type: "SUV", avgConsumptionLPer100km: 8.5 },
      { name: "Outlander", type: "SUV", avgConsumptionLPer100km: 9.5 },
      { name: "Montero / Pajero", type: "SUV", avgConsumptionLPer100km: 12.0 },
      { name: "L200 2.5/2.4 TDi", type: "pickup", avgConsumptionLPer100km: 9.8 },
    ],
  },
  {
    brand: "Motomel",
    models: [
      { name: "B110", type: "moto", avgConsumptionLPer100km: 2.5 },
      { name: "S2 150", type: "moto", avgConsumptionLPer100km: 3.0 },
      { name: "Sirius 190", type: "moto", avgConsumptionLPer100km: 3.5 },
      { name: "Skua 150/250", type: "moto", avgConsumptionLPer100km: 3.8 },
    ],
  },
  {
    brand: "Nissan",
    models: [
      { name: "March 1.6", type: "auto", avgConsumptionLPer100km: 7.4 },
      { name: "Note", type: "auto", avgConsumptionLPer100km: 7.0 },
      { name: "Versa 1.6", type: "auto", avgConsumptionLPer100km: 7.6 },
      { name: "Sentra 1.8/2.0", type: "auto", avgConsumptionLPer100km: 8.0 },
      { name: "Altima", type: "auto", avgConsumptionLPer100km: 9.0 },
      { name: "370Z / Z", type: "deportivo", avgConsumptionLPer100km: 11.5 },
      { name: "GT-R", type: "deportivo", avgConsumptionLPer100km: 14.0 },
      { name: "Kicks 1.6", type: "SUV", avgConsumptionLPer100km: 8.2 },
      { name: "X-Trail", type: "SUV", avgConsumptionLPer100km: 9.5 },
      { name: "Murano", type: "SUV", avgConsumptionLPer100km: 11.0 },
      { name: "Frontier 2.3 TDi", type: "pickup", avgConsumptionLPer100km: 9.5 },
      { name: "Leaf (EV)", type: "auto", avgConsumptionLPer100km: 0.0 },
    ],
  },
  {
    brand: "Peugeot",
    models: [
      { name: "206 / 207 Compact", type: "auto", avgConsumptionLPer100km: 7.5 },
      { name: "208 1.2/1.6/1.0 T", type: "auto", avgConsumptionLPer100km: 7.2 },
      { name: "208 GT", type: "deportivo", avgConsumptionLPer100km: 7.8 },
      { name: "2008 1.6/THP", type: "SUV", avgConsumptionLPer100km: 7.8 },
      { name: "308 1.6/THP", type: "auto", avgConsumptionLPer100km: 8.2 },
      { name: "308 S GTi", type: "deportivo", avgConsumptionLPer100km: 9.0 },
      { name: "408 1.6/THP", type: "auto", avgConsumptionLPer100km: 8.5 },
      { name: "3008", type: "SUV", avgConsumptionLPer100km: 8.0 },
      { name: "5008", type: "SUV", avgConsumptionLPer100km: 8.5 },
      { name: "Partner 1.6/HDi", type: "utilitario", avgConsumptionLPer100km: 7.5 },
      { name: "Rifter", type: "utilitario", avgConsumptionLPer100km: 7.8 },
      { name: "Expert", type: "utilitario", avgConsumptionLPer100km: 8.5 },
      { name: "Boxer", type: "utilitario", avgConsumptionLPer100km: 10.0 },
    ],
  },
  {
    brand: "Porsche",
    models: [
      { name: "718 Cayman / Boxster", type: "deportivo", avgConsumptionLPer100km: 10.5 },
      { name: "911 Carrera / Turbo / GT3", type: "deportivo", avgConsumptionLPer100km: 12.5 },
      { name: "Panamera", type: "auto", avgConsumptionLPer100km: 11.0 },
      { name: "Macan / Macan S", type: "SUV", avgConsumptionLPer100km: 10.5 },
      { name: "Cayenne / Coupe", type: "SUV", avgConsumptionLPer100km: 12.5 },
      { name: "Taycan (EV)", type: "deportivo", avgConsumptionLPer100km: 0.0 },
    ],
  },
  {
    brand: "RAM",
    models: [
      { name: "Rampage 2.0 T", type: "pickup", avgConsumptionLPer100km: 10.0 },
      { name: "1500 Laramie 5.7 V8", type: "pickup", avgConsumptionLPer100km: 16.0 },
      { name: "1500 Rebel (Híbrida)", type: "pickup", avgConsumptionLPer100km: 14.0 },
      { name: "2500 6.7 TDi", type: "pickup", avgConsumptionLPer100km: 18.0 },
    ],
  },
  {
    brand: "Renault",
    models: [
      { name: "Clio Mio/Clio 1.2/1.6", type: "auto", avgConsumptionLPer100km: 7.8 },
      { name: "Kwid 1.0", type: "auto", avgConsumptionLPer100km: 6.5 },
      { name: "Sandero/Stepway 1.6", type: "auto", avgConsumptionLPer100km: 8.0 },
      { name: "Sandero RS", type: "deportivo", avgConsumptionLPer100km: 9.5 },
      { name: "Logan 1.6", type: "auto", avgConsumptionLPer100km: 8.0 },
      { name: "Megane III / IV", type: "auto", avgConsumptionLPer100km: 8.5 },
      { name: "Fluence 1.6/2.0/GT", type: "auto", avgConsumptionLPer100km: 9.0 },
      { name: "Kangoo 1.6/1.5 dCi", type: "utilitario", avgConsumptionLPer100km: 7.5 },
      { name: "Duster 1.6/2.0/1.3 T", type: "SUV", avgConsumptionLPer100km: 8.8 },
      { name: "Captur 1.6/2.0/1.3 T", type: "SUV", avgConsumptionLPer100km: 8.5 },
      { name: "Koleos", type: "SUV", avgConsumptionLPer100km: 10.0 },
      { name: "Oroch 1.6/2.0/1.3 T", type: "pickup", avgConsumptionLPer100km: 9.0 },
      { name: "Alaskan 2.3 TDi", type: "pickup", avgConsumptionLPer100km: 9.5 },
      { name: "Master", type: "utilitario", avgConsumptionLPer100km: 11.0 },
    ],
  },
  {
    brand: "Rover",
    models: [
      { name: "200 Series (214/216)", type: "auto", avgConsumptionLPer100km: 9.0 },
      { name: "400 Series / 45", type: "auto", avgConsumptionLPer100km: 9.5 },
      { name: "600 Series / 75", type: "auto", avgConsumptionLPer100km: 10.0 },
      { name: "Mini (Classic)", type: "auto", avgConsumptionLPer100km: 7.0 },
    ],
  },
  {
    brand: "Scania",
    models: [
      { name: "P Series", type: "camion", avgConsumptionLPer100km: 26.0 },
      { name: "G Series", type: "camion", avgConsumptionLPer100km: 27.0 },
      { name: "R Series 420/440/450", type: "camion", avgConsumptionLPer100km: 28.0 },
      { name: "S Series 500/540", type: "camion", avgConsumptionLPer100km: 29.0 },
    ],
  },
  {
    brand: "Seat",
    models: [
      { name: "Ibiza 1.4/1.6", type: "auto", avgConsumptionLPer100km: 7.5 },
      { name: "Córdoba 1.6/TDi", type: "auto", avgConsumptionLPer100km: 7.0 },
      { name: "León 1.8/2.0 TSI/FR/Cupra", type: "auto", avgConsumptionLPer100km: 8.5 },
      { name: "Arona", type: "SUV", avgConsumptionLPer100km: 7.5 },
      { name: "Ateca", type: "SUV", avgConsumptionLPer100km: 8.5 },
    ],
  },
  {
    brand: "Simca",
    models: [
      { name: "1000", type: "auto", avgConsumptionLPer100km: 10.0 },
      { name: "Ariane", type: "auto", avgConsumptionLPer100km: 11.0 },
    ],
  },
  {
    brand: "Subaru",
    models: [
      { name: "Impreza 2.0", type: "auto", avgConsumptionLPer100km: 9.0 },
      { name: "WRX / STI", type: "deportivo", avgConsumptionLPer100km: 12.0 },
      { name: "XV / Crosstrek", type: "SUV", avgConsumptionLPer100km: 9.0 },
      { name: "Forester 2.0/2.5", type: "SUV", avgConsumptionLPer100km: 9.8 },
      { name: "Outback", type: "SUV", avgConsumptionLPer100km: 10.5 },
    ],
  },
  {
    brand: "Suzuki",
    models: [
      { name: "Swift 1.2/1.4/1.6", type: "auto", avgConsumptionLPer100km: 7.0 },
      { name: "Baleno", type: "auto", avgConsumptionLPer100km: 6.8 },
      { name: "Fun/Corsa II (Suzuki motor)", type: "auto", avgConsumptionLPer100km: 7.8 },
      { name: "Jimny", type: "SUV", avgConsumptionLPer100km: 7.5 },
      { name: "Vitara / Grand Vitara", type: "SUV", avgConsumptionLPer100km: 10.0 },
    ],
  },
  {
    brand: "Toyota",
    models: [
      { name: "Etios 1.5", type: "auto", avgConsumptionLPer100km: 7.2 },
      { name: "Yaris 1.5", type: "auto", avgConsumptionLPer100km: 7.2 },
      { name: "Corolla 1.8/2.0", type: "auto", avgConsumptionLPer100km: 7.4 },
      { name: "Corolla Hybrid", type: "auto", avgConsumptionLPer100km: 4.5 },
      { name: "Prius", type: "auto", avgConsumptionLPer100km: 4.2 },
      { name: "Camry / Camry Hybrid", type: "auto", avgConsumptionLPer100km: 6.5 },
      { name: "86 / GR86", type: "deportivo", avgConsumptionLPer100km: 9.0 },
      { name: "Corolla Cross 2.0/Hybrid", type: "SUV", avgConsumptionLPer100km: 6.0 },
      { name: "RAV4 Hybrid", type: "SUV", avgConsumptionLPer100km: 6.0 },
      { name: "SW4 2.8 TDi", type: "SUV", avgConsumptionLPer100km: 9.8 },
      { name: "Land Cruiser Prado/300", type: "SUV", avgConsumptionLPer100km: 12.0 },
      { name: "Hilux 2.4/2.8 TDi", type: "pickup", avgConsumptionLPer100km: 9.0 },
      { name: "Hiace", type: "utilitario", avgConsumptionLPer100km: 10.0 },
    ],
  },
  {
    brand: "Volkswagen",
    models: [
      { name: "Gol/Gol Trend 1.6", type: "auto", avgConsumptionLPer100km: 8.0 },
      { name: "Voyage", type: "auto", avgConsumptionLPer100km: 8.0 },
      { name: "Up! 1.0 / 1.0 TSI", type: "auto", avgConsumptionLPer100km: 6.5 },
      { name: "Fox / Suran", type: "auto", avgConsumptionLPer100km: 8.2 },
      { name: "Polo 1.6/1.0 TSI/GTS", type: "auto", avgConsumptionLPer100km: 7.6 },
      { name: "Virtus 1.6/1.0 TSI/GTS", type: "auto", avgConsumptionLPer100km: 7.6 },
      { name: "Golf 1.4 TSI/GTI", type: "auto", avgConsumptionLPer100km: 7.5 },
      { name: "Vento 1.4/2.0 TSI/GLI", type: "auto", avgConsumptionLPer100km: 7.8 },
      { name: "Passat", type: "auto", avgConsumptionLPer100km: 8.5 },
      { name: "Nivus 1.0 TSI/170", type: "SUV", avgConsumptionLPer100km: 7.5 },
      { name: "T-Cross 1.0 TSI", type: "SUV", avgConsumptionLPer100km: 7.8 },
      { name: "Taos 1.4 TSI", type: "SUV", avgConsumptionLPer100km: 8.5 },
      { name: "Tiguan Allspace 1.4/2.0 TSI", type: "SUV", avgConsumptionLPer100km: 9.0 },
      { name: "Touareg", type: "SUV", avgConsumptionLPer100km: 11.0 },
      { name: "Amarok 2.0/V6 TDi", type: "pickup", avgConsumptionLPer100km: 10.5 },
      { name: "Saveiro", type: "pickup", avgConsumptionLPer100km: 8.0 },
    ],
  },
  {
    brand: "Volvo",
    models: [
      { name: "V40", type: "auto", avgConsumptionLPer100km: 7.5 },
      { name: "S60 T4/T5", type: "auto", avgConsumptionLPer100km: 8.0 },
      { name: "S90", type: "auto", avgConsumptionLPer100km: 8.5 },
      { name: "XC40 / C40", type: "SUV", avgConsumptionLPer100km: 8.5 },
      { name: "XC60", type: "SUV", avgConsumptionLPer100km: 9.0 },
      { name: "XC90", type: "SUV", avgConsumptionLPer100km: 10.0 },
    ],
  },
  {
    brand: "Yamaha",
    models: [
      { name: "Crypton 110", type: "moto", avgConsumptionLPer100km: 2.5 },
      { name: "YBR 125 / Z", type: "moto", avgConsumptionLPer100km: 2.8 },
      { name: "FZ / FZ-S FI", type: "moto", avgConsumptionLPer100km: 3.0 },
      { name: "XTZ 125/250", type: "moto", avgConsumptionLPer100km: 3.5 },
      { name: "MT-03", type: "moto", avgConsumptionLPer100km: 4.2 },
      { name: "MT-07", type: "moto", avgConsumptionLPer100km: 5.0 },
      { name: "MT-09", type: "moto", avgConsumptionLPer100km: 5.8 },
    ],
  },
]
